{
    "name": "RSD Polymer Production",
    'icon': '/rsd_sales/static/description/icon.png',
    "version": "18.0.1.1",
    "summary": "Production Module Customization",
    'description': """
        This is RSD Polymer Customization module for Sales.
        """,
    'author': 'RSD Polymer',
    'website': 'https://www.rsdpolymers.com/',
    "depends": ["stock", "sale", "account", "rsd_sales", "mrp", "product", "hr"],
    "data": [
        "data/sequence.xml",
        "security/ir.model.access.csv",
        "reports/delivery_challan_report.xml",
        "reports/delivery_challan_template.xml",
        "reports/mo_label_report.xml",
        "reports/mo_label_template.xml",
        "reports/print_label_report.xml",
        "reports/print_label_template.xml",
        "reports/rm_issue_report.xml",
        "reports/rm_issue_template.xml",
        "reports/production_request_report.xml",
        "reports/production_request_template.xml",
        "views/mrp_production_views.xml",
        "views/sale_order_views.xml",
        "views/production_request_reject_wizard_views.xml",
        "views/production_request_views.xml",
        "views/production_request_mo_view.xml",
        "views/rm_issue_views.xml",
        "views/rm_return_views.xml",
        "views/stock_picking_views.xml",
        "views/production_dashboard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "rsd_production/static/src/js/production_dashboard.js",
            "rsd_production/static/src/xml/production_dashboard.xml",
            "rsd_production/static/src/js/production_dashboard.scss",
        ],
    },
    "installable": True,
    'application': False,
    'license': 'LGPL-3',
}
